### ISSUE TITLE
Proposal String #20

### ISSUE THREAD

**Issue by vnebelung** [Gitjas/Road_To_Discovery_for_SoD#3]
String #20

> The information you gathered is grave news, &lt;CHARNAME&gt;. The danger from Caelar's crusade is much more severe than the rampaging army we set out to stop! You did well to gather this intel in time.

Proposal:

> The information you gathered is grave news, &lt;CHARNAME&gt;. The danger from Caelar's crusade is much more severe than **that of the** rampaging army we set out to stop! You did well to gather this intel in time.

**Comment by Gitjas** [comment]
Thanks for the suggestion. Your suggestion is grammatically correct but very formal. We'll leave in the original phrase.
